language: objective-c
os:
  - osx_image: xcode9.1
  - osx_image: xcode9
script:
- xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration "$CONFIGURATION"
  -sdk "$SDK" -destination "$DESTINATION" -derivedDataPath build
  -enableCodeCoverage YES ENABLE_TESTABILITY=YES "$ACTION"
after_success:
- ruby Scripts/coverage.rb "$SCHEME"
- bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
env:
  matrix:
  - SDK=iphonesimulator DESTINATION='name=iPhone 4s,OS=8.4' ACTION=test
  - SDK=iphonesimulator DESTINATION='name=iPhone 4s,OS=9.3' ACTION=test
  - SDK=iphonesimulator DESTINATION='name=iPhone 5s,OS=10.3.1' ACTION=test
  - SDK=iphonesimulator DESTINATION='name=iPhone 7,OS=11.0' ACTION=test
  - SDK=appletvsimulator DESTINATION='name=Apple TV 1080p,OS=9.0' ACTION=test
  - SDK=appletvsimulator DESTINATION='name=Apple TV 1080p,OS=10.0' ACTION=test
  - SDK=appletvsimulator DESTINATION='name=Apple TV 1080p,OS=11.0' ACTION=test
  - SDK=macosx DESTINATION='platform=OS X,arch=x86_64' ACTION=test
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - WORKSPACE=RealmTypeSafeQuery.xcworkspace
  - SCHEME=RealmTypeSafeQuery
  - CONFIGURATION=Release
branches:
  only:
  - master
